Repository swapagarwal/geeksay, pull requests merged in 2022-10, with the labels that each got.

#378 Added 4 quotes
  geeksay.js
Labels: hacktober-accepted

#377 qoute added
  geeksay.js
Labels: hacktoberfest-invalid

#408 Improve the Mobile Responsive Version #380
  index.html
Labels: hacktober-accepted

#410 Add word pair functionality and some refactoring
  geeksay.js
  index.html
Labels: hacktoberfest-accepted
